### ISSUE TITLE
How to get the Ubuntu package, install instructions do not work

### ISSUE THREAD

**Issue by gordynorth** [cyberemissary/mdbtools#10]
The install page has instructions for adding a repository for installation of the package. 
The instruction "echo "deb http://apt.cyberemissary.com/ubuntu/ xenial main" | sudo btee -a /etc/apt/sources.list.d/apt.cyberemissary.com.list" does not seem to work. 
- The site apt.cyberemissary.com is not accessible 
- What is the btee command, I am new to Linux but this is not a command. 

The RPM can be downloaded and I was able to install on Linux Mint 18 using alien.

**Comment by pcav** [comment]
@cyberemissary I confrim, cyberemissary.com does not allow access, link apparently broken

**Comment by cyberemissary** [comment]
Forgot to setup DNS records. The url should be working correctly now.

**Comment by cyberemissary** [comment]
Fixed the instructions in Readme as well. Must have been half asleep when wrote them originally.
