### ISSUE TITLE
Releasing mdbtoolts 0.8?

### ISSUE THREAD

**Issue by pcav** [cyberemissary/mdbtools#17]
Thanks for your work on `mdbtools`. This solves one problem for us. It would seem good to merge your work upstream and release an updated mainstream version: any reason not to do so?
I'm available for help if necessary.
Cheers.

**Comment by evanmiller** [comment]
@pcav There are packaged releases of this fork here:

https://github.com/cyberemissary/mdbtools/releases

We would need the cooperation of @brianb to get the changes merged upstream.

**Comment by cyberemissary** [comment]
Mainstream version does not seem to be maintained anymore. Last commit there was in 2017.
